SELECT DATE_FORMAT(O.DATETIME, '%H') AS HOUR,
COUNT(*) AS COUNT FROM ANIMAL_OUTS O
WHERE DATE_FORMAT(O.DATETIME, '%H') >= '09' AND
DATE_FORMAT(DATETIME, '%H') < '20'
GROUP BY DATE_FORMAT(O.DATETIME, '%H')
ORDER BY DATE_FORMAT(O.DATETIME, '%H');