SELECT B.CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK B INNER JOIN BOOK_SALES S
ON B.BOOK_ID = S.BOOK_ID
WHERE DATE_FORMAT(S.SALES_DATE, '%Y-%m-%d') >= '2022-01-01' AND
DATE_FORMAT(S.SALES_DATE, '%Y-%m-%d') < '2022-02-01'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;